version: '3.7'
services:
  blog-app-backend-server:
    build: ./
    volumes:
      - ./app/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 6000:80
    depends_on:
      - blog-app-db

  blog-app-db:
    build: ./postgresql
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 55432:5432

